spring:
  application:
    name: wros
  thymeleaf:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/waste_removal
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/waste_removal
    user: postgres
    password: postgres

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  order:
    fixed-cost-points: 100
